/*

 CAVEENTRENCEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 36
   Tile set      : C:\Users\markl\OneDrive\Documents\PROJECTS\wizard\sprites\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define CaveEntrenceMapWidth 100
#define CaveEntrenceMapHeight 36
#define CaveEntrenceMapBank 0

extern unsigned char CaveEntrenceMap[];

/* End of CAVEENTRENCEMAP.H */
