/*

 CAVE-ENTRENCE-MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 36
   Tile set      : C:\Users\markl\OneDrive\Documents\PROJECTS\wizard\sprites\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Cave-Entrence-MapWidth 100
#define Cave-Entrence-MapHeight 36
#define Cave-Entrence-MapBank 0

extern unsigned char Cave-Entrence-Map[];

/* End of CAVE-ENTRENCE-MAP.H */
